services:
  AccountTest:
    image: vaibhavgopnar/accounttest
    ports:
      - "8083:8083"
    networks: 
      - bank-network
  Cards:
    image: vaibhavgopnar/cards
    ports:
      - "8081:8081"
    networks:
      - bank-network
  InsurancePolicy:
    image: vaibhavgopnar/insurancepolicy
    ports:
      - "8082:8082"
    networks:
      - bank-network
  LoanAppForUser:
    image: vaibhavgopnar/loanappforuser
    ports:
      - "8090:8090"
    networks:
      - bank-network
networks:
  bank-network: {}